name: Deploy ASP.NET App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish ASP.NET App
        run: dotnet publish -c Release -o ./publish

      - name: Copy Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./publish/*
          target: /var/www/aspnetapp/

      - name: Restart App
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@your-server-ip \
          "systemctl restart my-aspnet-app.service || echo 'No service to restart'"
